name: Setup WSL

on: [push, pull_request]

jobs:
  setup-wsl:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable virtualization
        run: |
         Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
      
      - name: Install WSL
        run: |
          wsl --install
        shell: pwsh
      
      - name: Check python in WSL
        run: |
          wsl
          python --version
        shell: pwsh

      - name: Setup WSL environment
        run: |
          wsl
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install -y nodejs
  
      - name: Force clean install dependencies
        run: wsl npm install --force

      - name: Start the server and run Cypress tests
        run: wsl npm start

      - name: Wait for server to be ready
        run: sleep 10

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate and upload system specs
        run: PowerShell -File ./export_system_specs.ps1

      - name: Upload system specs
        uses: actions/upload-artifact@v4
        with:
          name: system-specs
          path: system_specs.txt
